//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicaStudio.Viewer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReplicaStudio.Viewer.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static byte[] Arial10 {
            get {
                object obj = ResourceManager.GetObject("Arial10", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial11 {
            get {
                object obj = ResourceManager.GetObject("Arial11", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial12 {
            get {
                object obj = ResourceManager.GetObject("Arial12", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial14 {
            get {
                object obj = ResourceManager.GetObject("Arial14", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial16 {
            get {
                object obj = ResourceManager.GetObject("Arial16", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial18 {
            get {
                object obj = ResourceManager.GetObject("Arial18", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial20 {
            get {
                object obj = ResourceManager.GetObject("Arial20", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial24 {
            get {
                object obj = ResourceManager.GetObject("Arial24", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial28 {
            get {
                object obj = ResourceManager.GetObject("Arial28", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial32 {
            get {
                object obj = ResourceManager.GetObject("Arial32", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial36 {
            get {
                object obj = ResourceManager.GetObject("Arial36", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial42 {
            get {
                object obj = ResourceManager.GetObject("Arial42", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial8 {
            get {
                object obj = ResourceManager.GetObject("Arial8", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Arial9 {
            get {
                object obj = ResourceManager.GetObject("Arial9", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Debug {
            get {
                object obj = ResourceManager.GetObject("Debug", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] Debug2 {
            get {
                object obj = ResourceManager.GetObject("Debug2", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
