//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicaStudio.Editor.Culture.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EditorConstants {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EditorConstants() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReplicaStudio.Editor.Culture.Language.EditorConstants", typeof(EditorConstants).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string EVENTMANAGER_NO_CLASSES {
            get {
                return ResourceManager.GetString("EVENTMANAGER_NO_CLASSES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Success !.
        /// </summary>
        internal static string EXPORT_SUCCESS {
            get {
                return ResourceManager.GetString("EXPORT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        internal static string MOV_DOWN {
            get {
                return ResourceManager.GetString("MOV_DOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string MOV_LEFT {
            get {
                return ResourceManager.GetString("MOV_LEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left-Down.
        /// </summary>
        internal static string MOV_LEFTDOWN {
            get {
                return ResourceManager.GetString("MOV_LEFTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string MOV_RIGHT {
            get {
                return ResourceManager.GetString("MOV_RIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right-Down.
        /// </summary>
        internal static string MOV_RIGHTDOWN {
            get {
                return ResourceManager.GetString("MOV_RIGHTDOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        internal static string MOV_UP {
            get {
                return ResourceManager.GetString("MOV_UP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Left.
        /// </summary>
        internal static string MOV_UPLEFT {
            get {
                return ResourceManager.GetString("MOV_UPLEFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up-Right.
        /// </summary>
        internal static string MOV_UPRIGHT {
            get {
                return ResourceManager.GetString("MOV_UPRIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations.
        /// </summary>
        internal static string PROJECTPANEL_ANIMATIONS {
            get {
                return ResourceManager.GetString("PROJECTPANEL_ANIMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string PROJECTPANEL_CHARACTERS {
            get {
                return ResourceManager.GetString("PROJECTPANEL_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decors.
        /// </summary>
        internal static string PROJECTPANEL_DECORS {
            get {
                return ResourceManager.GetString("PROJECTPANEL_DECORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Musics.
        /// </summary>
        internal static string PROJECTPANEL_MUSICS {
            get {
                return ResourceManager.GetString("PROJECTPANEL_MUSICS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stages.
        /// </summary>
        internal static string PROJECTPANEL_STAGES {
            get {
                return ResourceManager.GetString("PROJECTPANEL_STAGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animations.
        /// </summary>
        internal static string STAGEOBJECTSPANEL_ANIMATIONS {
            get {
                return ResourceManager.GetString("STAGEOBJECTSPANEL_ANIMATIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string STAGEOBJECTSPANEL_CHARACTERS {
            get {
                return ResourceManager.GetString("STAGEOBJECTSPANEL_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decors.
        /// </summary>
        internal static string STAGEOBJECTSPANEL_DECORS {
            get {
                return ResourceManager.GetString("STAGEOBJECTSPANEL_DECORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hotspots.
        /// </summary>
        internal static string STAGEOBJECTSPANEL_HOTSPOTS {
            get {
                return ResourceManager.GetString("STAGEOBJECTSPANEL_HOTSPOTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regions.
        /// </summary>
        internal static string STAGEOBJECTSPANEL_REGIONS {
            get {
                return ResourceManager.GetString("STAGEOBJECTSPANEL_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Walkable areas.
        /// </summary>
        internal static string STAGEOBJECTSPANEL_WALKABLE {
            get {
                return ResourceManager.GetString("STAGEOBJECTSPANEL_WALKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu which propose help or information about the soft..
        /// </summary>
        internal static string STATUS_DESC_ABOUT {
            get {
                return ResourceManager.GetString("STATUS_DESC_ABOUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a popup that gives information about the dev team..
        /// </summary>
        internal static string STATUS_DESC_ABOUTUS {
            get {
                return ResourceManager.GetString("STATUS_DESC_ABOUTUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu which propose to export the project to different locations. Currently only Windows OS are supported..
        /// </summary>
        internal static string STATUS_DESC_BUILD {
            get {
                return ResourceManager.GetString("STATUS_DESC_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu which propose to try the game either in a normal mode or a fullscreen mode..
        /// </summary>
        internal static string STATUS_DESC_BUILDTOWINDOWS {
            get {
                return ResourceManager.GetString("STATUS_DESC_BUILDTOWINDOWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the circle tool to draw circles for hidden events or walkable areas..
        /// </summary>
        internal static string STATUS_DESC_CIRCLE {
            get {
                return ResourceManager.GetString("STATUS_DESC_CIRCLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy an object and keep it in memory to be pasted later..
        /// </summary>
        internal static string STATUS_DESC_COPY {
            get {
                return ResourceManager.GetString("STATUS_DESC_COPY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a popup to create a new map..
        /// </summary>
        internal static string STATUS_DESC_CREATEMAP {
            get {
                return ResourceManager.GetString("STATUS_DESC_CREATEMAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an object and keep it in memory to be pasted later..
        /// </summary>
        internal static string STATUS_DESC_CUT {
            get {
                return ResourceManager.GetString("STATUS_DESC_CUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the database window, which allow you to modify all the game system resources..
        /// </summary>
        internal static string STATUS_DESC_DATABASE {
            get {
                return ResourceManager.GetString("STATUS_DESC_DATABASE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete an object..
        /// </summary>
        internal static string STATUS_DESC_DELETE {
            get {
                return ResourceManager.GetString("STATUS_DESC_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a documentation to help to get started with the soft..
        /// </summary>
        internal static string STATUS_DESC_DOCUMENT {
            get {
                return ResourceManager.GetString("STATUS_DESC_DOCUMENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu to choose a tool to draw an hidden event or walkable areas..
        /// </summary>
        internal static string STATUS_DESC_DRAWING {
            get {
                return ResourceManager.GetString("STATUS_DESC_DRAWING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu to do the cut/copy/paste operations..
        /// </summary>
        internal static string STATUS_DESC_EDITION {
            get {
                return ResourceManager.GetString("STATUS_DESC_EDITION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave the application..
        /// </summary>
        internal static string STATUS_DESC_EXIT {
            get {
                return ResourceManager.GetString("STATUS_DESC_EXIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu to manage a project, access to the general settings or leave the application..
        /// </summary>
        internal static string STATUS_DESC_FILE {
            get {
                return ResourceManager.GetString("STATUS_DESC_FILE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile the game and launch it in a fullscreen mode..
        /// </summary>
        internal static string STATUS_DESC_FULLSCREEN_TRY {
            get {
                return ResourceManager.GetString("STATUS_DESC_FULLSCREEN_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu which propose to try the game either in a normal mode or a fullscreen mode..
        /// </summary>
        internal static string STATUS_DESC_GAME {
            get {
                return ResourceManager.GetString("STATUS_DESC_GAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a popup to change some general settings of the application..
        /// </summary>
        internal static string STATUS_DESC_GENERALSETTINGS {
            get {
                return ResourceManager.GetString("STATUS_DESC_GENERALSETTINGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a popup to choose a mask file to import within the current stage..
        /// </summary>
        internal static string STATUS_DESC_IMPORTMASK {
            get {
                return ResourceManager.GetString("STATUS_DESC_IMPORTMASK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide informations about the selected object within the stage, or the stage itself if nothing is selected..
        /// </summary>
        internal static string STATUS_DESC_INFOPANEL {
            get {
                return ResourceManager.GetString("STATUS_DESC_INFOPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu which propose to change the language.
        /// </summary>
        internal static string STATUS_DESC_LANGUAGE {
            get {
                return ResourceManager.GetString("STATUS_DESC_LANGUAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow you to create, edit or delete layers for the stage..
        /// </summary>
        internal static string STATUS_DESC_LAYERSPANEL {
            get {
                return ResourceManager.GetString("STATUS_DESC_LAYERSPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load a project and all its stages..
        /// </summary>
        internal static string STATUS_DESC_LOAD {
            get {
                return ResourceManager.GetString("STATUS_DESC_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu to choose the edition mode for the stage..
        /// </summary>
        internal static string STATUS_DESC_MODE {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the edition mode for the stage to Characters, which allow you to place character objects. Hidden events and areas are not shown..
        /// </summary>
        internal static string STATUS_DESC_MODE_CHARACTERS {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE_CHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the edition mode for the stage to Decors, which allow you to place decors. Objects, hidden events and areas are not shown..
        /// </summary>
        internal static string STATUS_DESC_MODE_DECORS {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE_DECORS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the edition mode for the stage to Events, which allow you to place hidden events. Walkable areas and regions are not shown..
        /// </summary>
        internal static string STATUS_DESC_MODE_EVENTS {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE_EVENTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the edition mode for the stage to Objects, which allow you to place animation objects. Hidden events and areas are not shown..
        /// </summary>
        internal static string STATUS_DESC_MODE_OBJECTS {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE_OBJECTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the edition mode for the stage to Regions, which allow you to create new areas and set percentage of zoom on characters sprites depending on how far they are from the main region (zoom 100%). Hidden events and walkable areas are not shown..
        /// </summary>
        internal static string STATUS_DESC_MODE_REGIONS {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE_REGIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the edition mode for the stage to Walkable Areas, which allow you to specify where the player character can/can&apos;t move. Hidden events and regions are not shown..
        /// </summary>
        internal static string STATUS_DESC_MODE_WALKABLE {
            get {
                return ResourceManager.GetString("STATUS_DESC_MODE_WALKABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open a popup to create a new project..
        /// </summary>
        internal static string STATUS_DESC_NEW {
            get {
                return ResourceManager.GetString("STATUS_DESC_NEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste an object that has been kept in memory by a cut/copy action..
        /// </summary>
        internal static string STATUS_DESC_PASTE {
            get {
                return ResourceManager.GetString("STATUS_DESC_PASTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the pencil tool to draw areas for hidden events or walkable areas..
        /// </summary>
        internal static string STATUS_DESC_PENCIL {
            get {
                return ResourceManager.GetString("STATUS_DESC_PENCIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the pointer tool to select pointers made by the pencil, rectangle or circle tool for hidden events or walkable areas..
        /// </summary>
        internal static string STATUS_DESC_POINTER {
            get {
                return ResourceManager.GetString("STATUS_DESC_POINTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide a preview of the selected objet in the stage..
        /// </summary>
        internal static string STATUS_DESC_PREVIEWPANEL {
            get {
                return ResourceManager.GetString("STATUS_DESC_PREVIEWPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to drag &amp; drop objects to the stage. It also lists all the stage that can be loaded with a double click on a stage name..
        /// </summary>
        internal static string STATUS_DESC_PROJECTPANEL {
            get {
                return ResourceManager.GetString("STATUS_DESC_PROJECTPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the rectangle tool to draw rectangles for hidden events or walkable areas..
        /// </summary>
        internal static string STATUS_DESC_RECTANGLE {
            get {
                return ResourceManager.GetString("STATUS_DESC_RECTANGLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu which propose to create a map or access to the Database or the Resources Manager..
        /// </summary>
        internal static string STATUS_DESC_RESOURCES {
            get {
                return ResourceManager.GetString("STATUS_DESC_RESOURCES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the Resources Manager window, which allow you to import, preview or delete physical resources such as pictures or musics..
        /// </summary>
        internal static string STATUS_DESC_RESOURCESMANAGER {
            get {
                return ResourceManager.GetString("STATUS_DESC_RESOURCESMANAGER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save a project and all its stages..
        /// </summary>
        internal static string STATUS_DESC_SAVE {
            get {
                return ResourceManager.GetString("STATUS_DESC_SAVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch the external tool &quot;Sprite Creator&quot; which help creating character animations.
        /// </summary>
        internal static string STATUS_DESC_SPRITECREATOR {
            get {
                return ResourceManager.GetString("STATUS_DESC_SPRITECREATOR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to manage objects within the stage or add events in it..
        /// </summary>
        internal static string STATUS_DESC_STAGE {
            get {
                return ResourceManager.GetString("STATUS_DESC_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide you a view of all objects in the stage..
        /// </summary>
        internal static string STATUS_DESC_STAGEOBJECTSPANEL {
            get {
                return ResourceManager.GetString("STATUS_DESC_STAGEOBJECTSPANEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compile the game and launch it in a windowed mode..
        /// </summary>
        internal static string STATUS_DESC_TRY {
            get {
                return ResourceManager.GetString("STATUS_DESC_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu to manage the windows settings of the application..
        /// </summary>
        internal static string STATUS_DESC_VIEW {
            get {
                return ResourceManager.GetString("STATUS_DESC_VIEW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide the toolbar on the left..
        /// </summary>
        internal static string STATUS_DESC_VIEW_LEFT_BAR {
            get {
                return ResourceManager.GetString("STATUS_DESC_VIEW_LEFT_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide the toolbar on the right..
        /// </summary>
        internal static string STATUS_DESC_VIEW_RIGHT_BAR {
            get {
                return ResourceManager.GetString("STATUS_DESC_VIEW_RIGHT_BAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide the toolbar in the menu..
        /// </summary>
        internal static string STATUS_DESC_VIEW_TOOLBAR {
            get {
                return ResourceManager.GetString("STATUS_DESC_VIEW_TOOLBAR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the website of Replica Studio..
        /// </summary>
        internal static string STATUS_DESC_WEBSITE {
            get {
                return ResourceManager.GetString("STATUS_DESC_WEBSITE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand a submenu to choose a zoom to apply to the stage edition..
        /// </summary>
        internal static string STATUS_DESC_ZOOM {
            get {
                return ResourceManager.GetString("STATUS_DESC_ZOOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a zoom of 100% to the stage edition..
        /// </summary>
        internal static string STATUS_DESC_ZOOM11 {
            get {
                return ResourceManager.GetString("STATUS_DESC_ZOOM11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a zoom of 200% to the stage edition..
        /// </summary>
        internal static string STATUS_DESC_ZOOM12 {
            get {
                return ResourceManager.GetString("STATUS_DESC_ZOOM12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a zoom of 400% to the stage edition..
        /// </summary>
        internal static string STATUS_DESC_ZOOM14 {
            get {
                return ResourceManager.GetString("STATUS_DESC_ZOOM14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply a zoom of 800% to the stage edition..
        /// </summary>
        internal static string STATUS_DESC_ZOOM18 {
            get {
                return ResourceManager.GetString("STATUS_DESC_ZOOM18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string TERM_CHOICENEXT {
            get {
                return ResourceManager.GetString("TERM_CHOICENEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string TERM_CHOICEPREVIOUS {
            get {
                return ResourceManager.GetString("TERM_CHOICEPREVIOUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Game.
        /// </summary>
        internal static string TERM_LEAVEGAME {
            get {
                return ResourceManager.GetString("TERM_LEAVEGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Game.
        /// </summary>
        internal static string TERM_LOADGAME {
            get {
                return ResourceManager.GetString("TERM_LOADGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Game.
        /// </summary>
        internal static string TERM_NEWGAME {
            get {
                return ResourceManager.GetString("TERM_NEWGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        internal static string TERM_OPTIONS {
            get {
                return ResourceManager.GetString("TERM_OPTIONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to title screen.
        /// </summary>
        internal static string TERM_RETURNTITLE {
            get {
                return ResourceManager.GetString("TERM_RETURNTITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Game.
        /// </summary>
        internal static string TERM_SAVEGAME {
            get {
                return ResourceManager.GetString("TERM_SAVEGAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save State.
        /// </summary>
        internal static string TERM_SAVESTATE {
            get {
                return ResourceManager.GetString("TERM_SAVESTATE", resourceCulture);
            }
        }
    }
}
