//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicaStudio.Editor.Culture.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReplicaStudio.Editor.Culture.Language.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning : Cancelling will restore the Database to it&apos;s last saved state ! Are you sure to cancel ?.
        /// </summary>
        internal static string DATABASE_CANCEL_CHANGES {
            get {
                return ResourceManager.GetString("DATABASE_CANCEL_CHANGES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible to export : Some files cannot be deleted ! Please close opened files in export folder, if any, and retry export !.
        /// </summary>
        internal static string EXPORT_DELETE_FAIL {
            get {
                return ResourceManager.GetString("EXPORT_DELETE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files Exists in the selected folder ! Do you really want to export ? All files will be overwritten !.
        /// </summary>
        internal static string EXPORT_FILES_EXISTS {
            get {
                return ResourceManager.GetString("EXPORT_FILES_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were some project integrity errors :.
        /// </summary>
        internal static string INTEGRITY_FAILED {
            get {
                return ResourceManager.GetString("INTEGRITY_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to load another project ? Unsaved changes will be definitely lost !.
        /// </summary>
        internal static string LOAD_PROJECT {
            get {
                return ResourceManager.GetString("LOAD_PROJECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select one character !.
        /// </summary>
        internal static string NO_CHARACTER_SELECTION {
            get {
                return ResourceManager.GetString("NO_CHARACTER_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must select a global event !.
        /// </summary>
        internal static string NO_GLOBALEVENT_SELECTION {
            get {
                return ResourceManager.GetString("NO_GLOBALEVENT_SELECTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        internal static string NOTIFICATION {
            get {
                return ResourceManager.GetString("NOTIFICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A project already exists in that folder, overwrite ?.
        /// </summary>
        internal static string PROJECT_EXIST {
            get {
                return ResourceManager.GetString("PROJECT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save your project? Any unsaved changes will be permanently lost !.
        /// </summary>
        internal static string PROJECT_LEAVE_APP {
            get {
                return ResourceManager.GetString("PROJECT_LEAVE_APP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To try your game, your current project must be saved. Do you want to continue ?.
        /// </summary>
        internal static string PROJECT_TRY {
            get {
                return ResourceManager.GetString("PROJECT_TRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete this stage ?.
        /// </summary>
        internal static string STAGE_DELETE {
            get {
                return ResourceManager.GetString("STAGE_DELETE", resourceCulture);
            }
        }
    }
}
