//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReplicaStudio.Shared.Culture.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ProjectIntegrity {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ProjectIntegrity() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReplicaStudio.Shared.Culture.Language.ProjectIntegrity", typeof(ProjectIntegrity).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playable Character [{0}], Starting Stage not set !.
        /// </summary>
        internal static string CHECK_PLAYABLECHARACTER_MAP {
            get {
                return ResourceManager.GetString("CHECK_PLAYABLECHARACTER_MAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a GUI System resource for your project !.
        /// </summary>
        internal static string GUI_SYSTEM_NEEDED {
            get {
                return ResourceManager.GetString("GUI_SYSTEM_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Database :.
        /// </summary>
        internal static string INTEGRITY_DATABASEZONE {
            get {
                return ResourceManager.GetString("INTEGRITY_DATABASEZONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Stages :.
        /// </summary>
        internal static string INTEGRITY_STAGE {
            get {
                return ResourceManager.GetString("INTEGRITY_STAGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Object Mode) On the stage [{0}], layer [{1}], animation [{2}], the script on [Page {3}] is invalid !.
        /// </summary>
        internal static string SCRIPT_ANIMATION {
            get {
                return ResourceManager.GetString("SCRIPT_ANIMATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GameOver Script is invalid !.
        /// </summary>
        internal static string SCRIPT_GAMEOVER {
            get {
                return ResourceManager.GetString("SCRIPT_GAMEOVER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The GlobalEvent Script [{0}] is invalid !.
        /// </summary>
        internal static string SCRIPT_GLOBALEVENT {
            get {
                return ResourceManager.GetString("SCRIPT_GLOBALEVENT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item Script [{0}], Action [{1}] is invalid !.
        /// </summary>
        internal static string SCRIPT_ITEM {
            get {
                return ResourceManager.GetString("SCRIPT_ITEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Item Interaction Script beetween Item [{0}] and Item [{1}] is invalid !.
        /// </summary>
        internal static string SCRIPT_ITEMINTERACTION {
            get {
                return ResourceManager.GetString("SCRIPT_ITEMINTERACTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Character Mode)  On the stage [{0}], Character [{1}], the script on [Page {2}] is invalid !.
        /// </summary>
        internal static string STAGE_SCRIPT_CHARACTER {
            get {
                return ResourceManager.GetString("STAGE_SCRIPT_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The ending script on stage [{0}] is invalid !.
        /// </summary>
        internal static string STAGE_SCRIPT_END {
            get {
                return ResourceManager.GetString("STAGE_SCRIPT_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first ending script on stage [{0}] is invalid !.
        /// </summary>
        internal static string STAGE_SCRIPT_END_FIRST {
            get {
                return ResourceManager.GetString("STAGE_SCRIPT_END_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Event Mode) On the stage [{0}], HotSpot [{1}], the script on [Page {2}] is invalid !.
        /// </summary>
        internal static string STAGE_SCRIPT_HOTSPOT {
            get {
                return ResourceManager.GetString("STAGE_SCRIPT_HOTSPOT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The starting script on stage [{0}] is invalid !.
        /// </summary>
        internal static string STAGE_SCRIPT_START {
            get {
                return ResourceManager.GetString("STAGE_SCRIPT_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first starting script on stage [{0}] is invalid !.
        /// </summary>
        internal static string STAGE_SCRIPT_START_FIRST {
            get {
                return ResourceManager.GetString("STAGE_SCRIPT_START_FIRST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a starting character in your project !.
        /// </summary>
        internal static string STARTING_CHARACTER_NEEDED {
            get {
                return ResourceManager.GetString("STARTING_CHARACTER_NEEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set a starting stage in your project !.
        /// </summary>
        internal static string STARTING_STAGE_NEEDED {
            get {
                return ResourceManager.GetString("STARTING_STAGE_NEEDED", resourceCulture);
            }
        }
    }
}
